included:
  - ios/

excluded:
  - Pods
  - Carthage
  - .build
  - ios/BudgetieApp/Preview Content

disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try
  - line_length
  - blanket_disable_command
  - large_tuple

opt_in_rules:
  - empty_count
  - first_where
  - discouraged_optional_boolean
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

analyzer_rules:
  - unused_import
  - explicit_self
  - redundant_optional_initialization
  - prefer_self_type_over_type_of_self

custom_rules:
  no_print:
    name: "No Print Statements"
    regex: 'print\(.*\)'
    message: "Avoid using print statements. Use os_log or Logger instead."
    severity: warning
