# Mocks configuration for Onboarding target

sources:
  - ./
templates:
  - ../../../../../../build/Sourcery/Templates/AutoMock.stencil
output:
    ../../Tests/AuthTests/Mocks
args:
  mockTestableImports: [Auth]
  mockImports: [AuthAPI]
