# Mocks configuration for Onboarding target

sources:
  - ./
templates:
  - ../../../../../../build/Sourcery/Templates/AutoMock.stencil
output:
    ../Mocks
args:
  mockTestableImports: [AppNavigationAPI]
